const createUsers = `	
  CREATE TABLE IF NOT EXISTS users (
	  id INTEGER PRIMARY KEY AUTOINCREMENT, /* UM DADO COM ID SENDO INTEIRO E UMA CHAVE COM ID AUTOMATICO*/
    name VARCHAR,
    email VARCHAR,
    password VARCHAR,
    avatar VARCHAR NULL, /* NULL PERMITE QUE O CAMPO SEJA OPCIONAL*/
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, /* PADRÃO DE DATA E A DATA ATUAL*/
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)`;

module.exports = createUsers;
